version: '3.8'

# docker-compose -f docker-compose-devdb.yaml build
# docker-compose -f docker-compose-devdb.yaml upd

services:
  db:
    container_name: pgdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stattron
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'