version: "3"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom

  redis:
    container_name: "redis"
    image: redislabs/redismod
    ports:
      - '6379:6379'

  redisinsight:
    container_name: "redisinsight"
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'


#  masternode:
#    build: ./MasterNode
#    container_name: masternode
#    command: gunicorn --bind 0.0.0.0:5000 main:app
#    volumes:
#      - ./masternode:/masternode
#    expose:
#      - 5000


#  nginx:
#    build: ./nginx
#    container_name: nginx_ssl
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./static:/home/www/default/static
#      - ./nginx/www/:/home/web/www
#    depends_on:
#      - masternode

  testdb:
    container_name: "testdb"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5432:5432"
    networks:
      - custom

  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - '5050:80'
      networks:
        - custom

networks:
  custom:
    driver: bridge
